/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutosaveRouteImport } from './routes/autosave'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CheckingRouteImport } from './routes/checking'
import { Route as CreditBuilderRouteImport } from './routes/credit-builder'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as PhysicalCardRouteImport } from './routes/physical-card'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as SpotmeRouteImport } from './routes/spotme'
import { Route as TransferRouteImport } from './routes/transfer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutosaveRoute = AutosaveRouteImport.update({
  id: '/autosave',
  path: '/autosave',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckingRoute = CheckingRouteImport.update({
  id: '/checking',
  path: '/checking',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditBuilderRoute = CreditBuilderRouteImport.update({
  id: '/credit-builder',
  path: '/credit-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicalCardRoute = PhysicalCardRouteImport.update({
  id: '/physical-card',
  path: '/physical-card',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotmeRoute = SpotmeRouteImport.update({
  id: '/spotme',
  path: '/spotme',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autosave': typeof AutosaveRoute
  '/cards': typeof CardsRoute
  '/checking': typeof CheckingRoute
  '/credit-builder': typeof CreditBuilderRoute
  '/insights': typeof InsightsRoute
  '/physical-card': typeof PhysicalCardRoute
  '/savings': typeof SavingsRoute
  '/spotme': typeof SpotmeRoute
  '/transfer': typeof TransferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autosave': typeof AutosaveRoute
  '/cards': typeof CardsRoute
  '/checking': typeof CheckingRoute
  '/credit-builder': typeof CreditBuilderRoute
  '/insights': typeof InsightsRoute
  '/physical-card': typeof PhysicalCardRoute
  '/savings': typeof SavingsRoute
  '/spotme': typeof SpotmeRoute
  '/transfer': typeof TransferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autosave': typeof AutosaveRoute
  '/cards': typeof CardsRoute
  '/checking': typeof CheckingRoute
  '/credit-builder': typeof CreditBuilderRoute
  '/insights': typeof InsightsRoute
  '/physical-card': typeof PhysicalCardRoute
  '/savings': typeof SavingsRoute
  '/spotme': typeof SpotmeRoute
  '/transfer': typeof TransferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autosave'
    | '/cards'
    | '/checking'
    | '/credit-builder'
    | '/insights'
    | '/physical-card'
    | '/savings'
    | '/spotme'
    | '/transfer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autosave'
    | '/cards'
    | '/checking'
    | '/credit-builder'
    | '/insights'
    | '/physical-card'
    | '/savings'
    | '/spotme'
    | '/transfer'
  id:
    | '__root__'
    | '/'
    | '/autosave'
    | '/cards'
    | '/checking'
    | '/credit-builder'
    | '/insights'
    | '/physical-card'
    | '/savings'
    | '/spotme'
    | '/transfer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutosaveRoute: typeof AutosaveRoute
  CardsRoute: typeof CardsRoute
  CheckingRoute: typeof CheckingRoute
  CreditBuilderRoute: typeof CreditBuilderRoute
  InsightsRoute: typeof InsightsRoute
  PhysicalCardRoute: typeof PhysicalCardRoute
  SavingsRoute: typeof SavingsRoute
  SpotmeRoute: typeof SpotmeRoute
  TransferRoute: typeof TransferRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autosave': {
      id: '/autosave'
      path: '/autosave'
      fullPath: '/autosave'
      preLoaderRoute: typeof AutosaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checking': {
      id: '/checking'
      path: '/checking'
      fullPath: '/checking'
      preLoaderRoute: typeof CheckingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-builder': {
      id: '/credit-builder'
      path: '/credit-builder'
      fullPath: '/credit-builder'
      preLoaderRoute: typeof CreditBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physical-card': {
      id: '/physical-card'
      path: '/physical-card'
      fullPath: '/physical-card'
      preLoaderRoute: typeof PhysicalCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotme': {
      id: '/spotme'
      path: '/spotme'
      fullPath: '/spotme'
      preLoaderRoute: typeof SpotmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutosaveRoute: AutosaveRoute,
  CardsRoute: CardsRoute,
  CheckingRoute: CheckingRoute,
  CreditBuilderRoute: CreditBuilderRoute,
  InsightsRoute: InsightsRoute,
  PhysicalCardRoute: PhysicalCardRoute,
  SavingsRoute: SavingsRoute,
  SpotmeRoute: SpotmeRoute,
  TransferRoute: TransferRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
