/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutosaveRouteImport } from './routes/autosave'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CheckingRouteImport } from './routes/checking'
import { Route as CreditBuilderRouteImport } from './routes/credit-builder'
import { Route as DepositCheckRouteImport } from './routes/deposit-check'
import { Route as GoalNewRouteImport } from './routes/goal-new'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LinkedAccountsRouteImport } from './routes/linked-accounts'
import { Route as MailCheckRouteImport } from './routes/mail-check'
import { Route as MoveRouteImport } from './routes/move'
import { Route as PhysicalCardRouteImport } from './routes/physical-card'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as SavingsMoveRouteImport } from './routes/savings-move'
import { Route as SpotmeRouteImport } from './routes/spotme'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as GoalIdRouteImport } from './routes/goal.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutosaveRoute = AutosaveRouteImport.update({
  id: '/autosave',
  path: '/autosave',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckingRoute = CheckingRouteImport.update({
  id: '/checking',
  path: '/checking',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditBuilderRoute = CreditBuilderRouteImport.update({
  id: '/credit-builder',
  path: '/credit-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositCheckRoute = DepositCheckRouteImport.update({
  id: '/deposit-check',
  path: '/deposit-check',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalNewRoute = GoalNewRouteImport.update({
  id: '/goal-new',
  path: '/goal-new',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedAccountsRoute = LinkedAccountsRouteImport.update({
  id: '/linked-accounts',
  path: '/linked-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const MailCheckRoute = MailCheckRouteImport.update({
  id: '/mail-check',
  path: '/mail-check',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveRoute = MoveRouteImport.update({
  id: '/move',
  path: '/move',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicalCardRoute = PhysicalCardRouteImport.update({
  id: '/physical-card',
  path: '/physical-card',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsMoveRoute = SavingsMoveRouteImport.update({
  id: '/savings-move',
  path: '/savings-move',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotmeRoute = SpotmeRouteImport.update({
  id: '/spotme',
  path: '/spotme',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalIdRoute = GoalIdRouteImport.update({
  id: '/goal/$id',
  path: '/goal/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autosave': typeof AutosaveRoute
  '/cards': typeof CardsRoute
  '/checking': typeof CheckingRoute
  '/credit-builder': typeof CreditBuilderRoute
  '/deposit-check': typeof DepositCheckRoute
  '/goal-new': typeof GoalNewRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/linked-accounts': typeof LinkedAccountsRoute
  '/mail-check': typeof MailCheckRoute
  '/move': typeof MoveRoute
  '/physical-card': typeof PhysicalCardRoute
  '/savings': typeof SavingsRoute
  '/savings-move': typeof SavingsMoveRoute
  '/spotme': typeof SpotmeRoute
  '/transfer': typeof TransferRoute
  '/goal/$id': typeof GoalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autosave': typeof AutosaveRoute
  '/cards': typeof CardsRoute
  '/checking': typeof CheckingRoute
  '/credit-builder': typeof CreditBuilderRoute
  '/deposit-check': typeof DepositCheckRoute
  '/goal-new': typeof GoalNewRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/linked-accounts': typeof LinkedAccountsRoute
  '/mail-check': typeof MailCheckRoute
  '/move': typeof MoveRoute
  '/physical-card': typeof PhysicalCardRoute
  '/savings': typeof SavingsRoute
  '/savings-move': typeof SavingsMoveRoute
  '/spotme': typeof SpotmeRoute
  '/transfer': typeof TransferRoute
  '/goal/$id': typeof GoalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autosave': typeof AutosaveRoute
  '/cards': typeof CardsRoute
  '/checking': typeof CheckingRoute
  '/credit-builder': typeof CreditBuilderRoute
  '/deposit-check': typeof DepositCheckRoute
  '/goal-new': typeof GoalNewRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/linked-accounts': typeof LinkedAccountsRoute
  '/mail-check': typeof MailCheckRoute
  '/move': typeof MoveRoute
  '/physical-card': typeof PhysicalCardRoute
  '/savings': typeof SavingsRoute
  '/savings-move': typeof SavingsMoveRoute
  '/spotme': typeof SpotmeRoute
  '/transfer': typeof TransferRoute
  '/goal/$id': typeof GoalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autosave'
    | '/cards'
    | '/checking'
    | '/credit-builder'
    | '/deposit-check'
    | '/goal-new'
    | '/inbox'
    | '/insights'
    | '/linked-accounts'
    | '/mail-check'
    | '/move'
    | '/physical-card'
    | '/savings'
    | '/savings-move'
    | '/spotme'
    | '/transfer'
    | '/goal/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autosave'
    | '/cards'
    | '/checking'
    | '/credit-builder'
    | '/deposit-check'
    | '/goal-new'
    | '/inbox'
    | '/insights'
    | '/linked-accounts'
    | '/mail-check'
    | '/move'
    | '/physical-card'
    | '/savings'
    | '/savings-move'
    | '/spotme'
    | '/transfer'
    | '/goal/$id'
  id:
    | '__root__'
    | '/'
    | '/autosave'
    | '/cards'
    | '/checking'
    | '/credit-builder'
    | '/deposit-check'
    | '/goal-new'
    | '/inbox'
    | '/insights'
    | '/linked-accounts'
    | '/mail-check'
    | '/move'
    | '/physical-card'
    | '/savings'
    | '/savings-move'
    | '/spotme'
    | '/transfer'
    | '/goal/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutosaveRoute: typeof AutosaveRoute
  CardsRoute: typeof CardsRoute
  CheckingRoute: typeof CheckingRoute
  CreditBuilderRoute: typeof CreditBuilderRoute
  DepositCheckRoute: typeof DepositCheckRoute
  GoalNewRoute: typeof GoalNewRoute
  InboxRoute: typeof InboxRoute
  InsightsRoute: typeof InsightsRoute
  LinkedAccountsRoute: typeof LinkedAccountsRoute
  MailCheckRoute: typeof MailCheckRoute
  MoveRoute: typeof MoveRoute
  PhysicalCardRoute: typeof PhysicalCardRoute
  SavingsRoute: typeof SavingsRoute
  SavingsMoveRoute: typeof SavingsMoveRoute
  SpotmeRoute: typeof SpotmeRoute
  TransferRoute: typeof TransferRoute
  GoalIdRoute: typeof GoalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autosave': {
      id: '/autosave'
      path: '/autosave'
      fullPath: '/autosave'
      preLoaderRoute: typeof AutosaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checking': {
      id: '/checking'
      path: '/checking'
      fullPath: '/checking'
      preLoaderRoute: typeof CheckingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-builder': {
      id: '/credit-builder'
      path: '/credit-builder'
      fullPath: '/credit-builder'
      preLoaderRoute: typeof CreditBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit-check': {
      id: '/deposit-check'
      path: '/deposit-check'
      fullPath: '/deposit-check'
      preLoaderRoute: typeof DepositCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal-new': {
      id: '/goal-new'
      path: '/goal-new'
      fullPath: '/goal-new'
      preLoaderRoute: typeof GoalNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linked-accounts': {
      id: '/linked-accounts'
      path: '/linked-accounts'
      fullPath: '/linked-accounts'
      preLoaderRoute: typeof LinkedAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail-check': {
      id: '/mail-check'
      path: '/mail-check'
      fullPath: '/mail-check'
      preLoaderRoute: typeof MailCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/move': {
      id: '/move'
      path: '/move'
      fullPath: '/move'
      preLoaderRoute: typeof MoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physical-card': {
      id: '/physical-card'
      path: '/physical-card'
      fullPath: '/physical-card'
      preLoaderRoute: typeof PhysicalCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings-move': {
      id: '/savings-move'
      path: '/savings-move'
      fullPath: '/savings-move'
      preLoaderRoute: typeof SavingsMoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotme': {
      id: '/spotme'
      path: '/spotme'
      fullPath: '/spotme'
      preLoaderRoute: typeof SpotmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal/$id': {
      id: '/goal/$id'
      path: '/goal/$id'
      fullPath: '/goal/$id'
      preLoaderRoute: typeof GoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutosaveRoute: AutosaveRoute,
  CardsRoute: CardsRoute,
  CheckingRoute: CheckingRoute,
  CreditBuilderRoute: CreditBuilderRoute,
  DepositCheckRoute: DepositCheckRoute,
  GoalNewRoute: GoalNewRoute,
  InboxRoute: InboxRoute,
  InsightsRoute: InsightsRoute,
  LinkedAccountsRoute: LinkedAccountsRoute,
  MailCheckRoute: MailCheckRoute,
  MoveRoute: MoveRoute,
  PhysicalCardRoute: PhysicalCardRoute,
  SavingsRoute: SavingsRoute,
  SavingsMoveRoute: SavingsMoveRoute,
  SpotmeRoute: SpotmeRoute,
  TransferRoute: TransferRoute,
  GoalIdRoute: GoalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
